create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null default 'RIVO User',
  avatar_url text,
  bio text default '',
  coins bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  topic text not null default '',
  owner_id uuid references public.profiles(id) on delete set null,
  is_private boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.room_members (
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'listener',
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.room_messages enable row level security;
alter table public.room_members enable row level security;

create policy "profiles readable" on public.profiles for select using (true);
create policy "own profile insert" on public.profiles for insert with check (auth.uid() = id);
create policy "own profile update" on public.profiles for update using (auth.uid() = id);
create policy "rooms readable" on public.rooms for select using (not is_private or owner_id = auth.uid());
create policy "signed in create room" on public.rooms for insert with check (auth.uid() = owner_id);
create policy "owner update room" on public.rooms for update using (auth.uid() = owner_id);
create policy "room messages readable" on public.room_messages for select using (true);
create policy "signed in send message" on public.room_messages for insert with check (auth.uid() = user_id);
create policy "members readable" on public.room_members for select using (true);
create policy "self join room" on public.room_members for insert with check (auth.uid() = user_id);
